In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('amazon_laptops.csv')

## 1. Data Cleaning

In [3]:
data.head(10)

,Title,Brand,ASIN,Thumbnail,Price,Rating,Display Size,operating_system,ram,disk_size,Reviews,Link
0,Mavark Dell Pro Max 18 Plus Mobile Workstation...,Mavark,B0FZ5VYS24,https://m.media-amazon.com/images/I/618uTk39ET...,"$14,999.00",NaN,18 inches,Windows 11 Pro,-,32 TB,NaN,https://www.amazon.com/Mavark-Mobile-Workstati...
1,Mavark Alienware 18 Area-51 Gaming Laptop Ultr...,Mavark,B0FY725M5R,https://m.media-amazon.com/images/I/71sS41Ho90...,"$12,999.00",NaN,18 inches,Windows 11 Pro,-,24 TB,NaN,https://www.amazon.com/Mavark-Alienware-Area-5...
2,Mavark Lenovo ThinkPad P16 Gen 3 Mobile Workst...,Mavark,B0G52VZBJ2,https://m.media-amazon.com/images/I/71zzzwVCEX...,"$11,999.00",NaN,16 inches,Windows 11 Pro,-,18 TB,NaN,https://www.amazon.com/Mavark-Lenovo-ThinkPad-...
3,Lenovo ThinkPad P17 Gen 2 Home & Business Lapt...,Lenovo,B0BG57VQ6V,https://m.media-amazon.com/images/I/81FTFyqo0R...,"$9,999.99",NaN,17.3 inches,Windows 11 Pro,16 GB,8 TB,NaN,https://www.amazon.com/Lenovo-ThinkPad-Busines...
4,[2026] MSI Titan 18 HX Dragon Edition Norse My...,[2026],B0GHRLM1TZ,https://m.media-amazon.com/images/I/71EOhAMuGY...,"$9,889.00",NaN,18 inches,Windows 11 Pro,128 GB,20 TB,NaN,https://www.amazon.com/Titan-Dragon-Norse-Myth...
5,"Lenovo Legion Pro 7i Gen 10 16"" Gaming Laptop ...",Lenovo,B0CG69MXZD,https://m.media-amazon.com/images/I/71aYDrY9pf...,"$9,199.98",5.0,16 inches,Windows 11 Pro,12,1 TB,1.0,https://www.amazon.com/Lenovo-IdeaPad-3i-Lapto...
6,"msi Titan AI Gaming Laptop 18"" 120Hz Mini LED ...",msi,B0FCM6RZQ9,https://m.media-amazon.com/images/I/61xjUAXxtk...,"$8,999.00",5.0,18 inches,Windows 11 Pro,64 GB,16 TB,1.0,https://www.amazon.com/msi-Gaming-Display-9-28...
7,"MSI Titan 18 HX AI A2XWJG-640CA 18"" UHD+ 120Hz...",MSI,B0FG46YVYP,https://m.media-amazon.com/images/I/71rzJZMnTv...,"$8,899.00",NaN,18 inches,Windows 11 Pro,-,6 TB,NaN,https://www.amazon.com/Titan-18-HX-AI-A2XWJG-6...
8,"ASUS ROG Strix Scar AI Gaming Laptop 18"" 240Hz...",ASUS,B0FCM6YNZ6,https://m.media-amazon.com/images/I/61X4XG7wuD...,"$8,174.99",NaN,18.00 inches,Windows 11 Pro,64 GB,16 TB,NaN,https://www.amazon.com/ASUS-Gaming-Display-9-2...
9,"ASUS ROG Strix Scar AI Gaming Laptop 18"" 240Hz...",ASUS,B0FCFY5KF5,https://m.media-amazon.com/images/I/71lwZswOu9...,"$8,094.99",NaN,18.00 inches,Windows 11 Pro,64 GB,16 TB,NaN,https://www.amazon.com/ASUS-Display-9-275HX-Pe...

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 328 entries, 0 to 327
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             328 non-null    object
 1   Brand             328 non-null    object
 2   ASIN              328 non-null    object
 3   Thumbnail         328 non-null    object
 4   Price             292 non-null    object
 5   Rating            64 non-null     float64
 6   Display Size      324 non-null    object
 7   operating_system  324 non-null    object
 8   ram               328 non-null    object
 9   disk_size         328 non-null    object
 10  Reviews           64 non-null     float64
 11  Link              328 non-null    object
dtypes: float64(2), object(10)
memory usage: 30.9+ KB

In [5]:
drop_columns = ['ASIN','Link','Thumbnail']
data.drop(drop_columns, axis=1, inplace=True)

In [6]:
data['Price']=data['Price'].str.replace('$','').str.replace(',','').astype(float)

In [7]:
data['display_size'] = data['Display Size'].str.replace(' inches','').astype(float)
data.drop('Display Size', axis=1, inplace=True)

In [8]:
data['disk_size'].value_counts()

disk_size
8 TB       76
4 TB       46
-          40
2 TB       30
0 GB       24
16 TB      22
1 TB       18
1000 GB    18
256 GB     17
2000 GB     8
128 GB      8
4000 GB     5
512 GB      4
6 TB        3
18 TB       2
20 TB       1
32 TB       1
24 TB       1
8000 TB     1
12 TB       1
8000 GB     1
3 TB        1
Name: count, dtype: int64

In [9]:
def clean_disk_size(x):
    x = str(x).lower().strip()

    if x =='-' or x =='0 gb':
        return 0 
    try:
        num = float(x.split()[0])
    except:
        return 0
    
    if 'tb' in x : 
        res = num * 1024
    else:
        res = num
    
    if res > 50000 : 
        res = res/1024

    return res

In [10]:
data['disk_size'] = data['disk_size'].apply(clean_disk_size)

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 328 entries, 0 to 327
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             328 non-null    object
 1   Brand             328 non-null    object
 2   Price             292 non-null    float64
 3   Rating            64 non-null     float64
 4   operating_system  324 non-null    object
 5   ram               328 non-null    object
 6   disk_size         328 non-null    float64
 7   Reviews           64 non-null     float64
 8   display_size      324 non-null    float64
dtypes: float64(5), object(4)
memory usage: 23.2+ KB

In [12]:
data['Price']= data['Price'].dropna()
data['Reviews'] =data['Reviews'].fillna(0).astype(int)  
data['ram'] = data['ram'].str.replace(' GB','')
data['ram'] = pd.to_numeric(data['ram'], errors='coerce')

In [13]:
data['ram'].fillna(0, inplace=True)
data.head()

C:\Users\Hp\AppData\Local\Temp\ipykernel_1720\1102460062.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['ram'].fillna(0, inplace=True)

,Title,Brand,Price,Rating,operating_system,ram,disk_size,Reviews,display_size
0,Mavark Dell Pro Max 18 Plus Mobile Workstation...,Mavark,14999.00,NaN,Windows 11 Pro,0.0,32768.0,0,18.0
1,Mavark Alienware 18 Area-51 Gaming Laptop Ultr...,Mavark,12999.00,NaN,Windows 11 Pro,0.0,24576.0,0,18.0
2,Mavark Lenovo ThinkPad P16 Gen 3 Mobile Workst...,Mavark,11999.00,NaN,Windows 11 Pro,0.0,18432.0,0,16.0
3,Lenovo ThinkPad P17 Gen 2 Home & Business Lapt...,Lenovo,9999.99,NaN,Windows 11 Pro,16.0,8192.0,0,17.3
4,[2026] MSI Titan 18 HX Dragon Edition Norse My...,[2026],9889.00,NaN,Windows 11 Pro,128.0,20480.0,0,18.0

## 2. Data Recovery

In [14]:
extracted_ram = data['Title'].str.extract(r'(\d+)\s*GB', expand=False).astype(float)

data.loc[data['ram'] == 0, 'ram'] = extracted_ram

In [15]:
data['ram'  ].value_counts()

ram
64.0     151
32.0      55
128.0     39
16.0      37
96.0      22
8.0       15
192.0      5
24.0       2
12.0       1
Name: count, dtype: int64

In [16]:
data['Brand'] = data['Brand'].str.upper().str.strip()

In [17]:
data['Brand'].value_counts()

Brand
LENOVO         70
ASUS           66
DELL           55
MSI            24
EXCALIBERPC    23
ALIENWARE      21
ACER           13
APPLE          13
HP             10
NEWLENOVO       7
NEW             6
MAVARK          4
GIGABYTE        3
ME2             2
RAZER           2
ROG             2
[2026]          1
NEWDE.L.L       1
MAINGEAR        1
[2025]          1
PANASONIC       1
TITAN           1
DORLAND         1
Name: count, dtype: int64

In [18]:
brand_map = {
    'NEWLENOVO': 'LENOVO',
    'NEW': 'LENOVO',
    'NEWDE.L.L': 'DELL',
    'ROG': 'ASUS',
    'TITAN': 'MSI'
}
data['Brand'] = data['Brand'].replace(brand_map)


def fix_brand_from_title(row):
    title = str(row['Title']).upper()
    brand = str(row['Brand']).upper()
    
    if brand in ['EXCALIBERPC', 'MAVARK', 'ME2', '[2025]', '[2026]']:
        if 'MSI' in title: return 'MSI'
        if 'DELL' in title: return 'DELL'
        if 'ASUS' in title: return 'ASUS'
        if 'LENOVO' in title: return 'LENOVO'
        if 'ACER' in title: return 'ACER'
        if 'APPLE' in title: return 'APPLE'
    return brand

data['Brand'] = data.apply(fix_brand_from_title, axis=1)

In [19]:
data.head(10)

,Title,Brand,Price,Rating,operating_system,ram,disk_size,Reviews,display_size
0,Mavark Dell Pro Max 18 Plus Mobile Workstation...,DELL,14999.00,NaN,Windows 11 Pro,24.0,32768.0,0,18.0
1,Mavark Alienware 18 Area-51 Gaming Laptop Ultr...,MAVARK,12999.00,NaN,Windows 11 Pro,96.0,24576.0,0,18.0
2,Mavark Lenovo ThinkPad P16 Gen 3 Mobile Workst...,LENOVO,11999.00,NaN,Windows 11 Pro,192.0,18432.0,0,16.0
3,Lenovo ThinkPad P17 Gen 2 Home & Business Lapt...,LENOVO,9999.99,NaN,Windows 11 Pro,16.0,8192.0,0,17.3
4,[2026] MSI Titan 18 HX Dragon Edition Norse My...,MSI,9889.00,NaN,Windows 11 Pro,128.0,20480.0,0,18.0
5,"Lenovo Legion Pro 7i Gen 10 16"" Gaming Laptop ...",LENOVO,9199.98,5.0,Windows 11 Pro,12.0,1024.0,1,16.0
6,"msi Titan AI Gaming Laptop 18"" 120Hz Mini LED ...",MSI,8999.00,5.0,Windows 11 Pro,64.0,16384.0,1,18.0
7,"MSI Titan 18 HX AI A2XWJG-640CA 18"" UHD+ 120Hz...",MSI,8899.00,NaN,Windows 11 Pro,64.0,6144.0,0,18.0
8,"ASUS ROG Strix Scar AI Gaming Laptop 18"" 240Hz...",ASUS,8174.99,NaN,Windows 11 Pro,64.0,16384.0,0,18.0
9,"ASUS ROG Strix Scar AI Gaming Laptop 18"" 240Hz...",ASUS,8094.99,NaN,Windows 11 Pro,64.0,16384.0,0,18.0

In [20]:
data['Brand'].value_counts()

Brand
LENOVO         84
ASUS           76
DELL           57
MSI            40
ALIENWARE      21
ACER           14
APPLE          13
HP             10
GIGABYTE        3
EXCALIBERPC     3
MAVARK          2
RAZER           2
MAINGEAR        1
PANASONIC       1
DORLAND         1
Name: count, dtype: int64

In [21]:
data['operating_system'].value_counts()

operating_system
Windows 11 Pro      206
Windows 11 Home      31
Windows 10 Pro       25
-                    23
Mac OS               13
Windows 11           13
Windows 10 Home       4
Others                3
Windows 10 or 11      3
P:Windows 11 Pro      3
Name: count, dtype: int64

In [22]:
os_map = {
    'P:Windows 11 Pro': 'Windows 11 Pro',
    'Windows 11': 'Windows 11 Pro',
    'Windows 10 or 11': 'Windows 11 Pro',
    '-': 'Unknown'
}
data['operating_system'] = data['operating_system'].replace(os_map)

def recover_os(row):
    if row['operating_system'] == 'Unknown':
        title = str(row['Title']).upper()
        if 'WINDOWS 11' in title: return 'Windows 11 Pro'
        if 'WINDOWS 10' in title: return 'Windows 10 Pro'
        if 'MAC' in title or 'APPLE' in title: return 'Mac OS'
    return row['operating_system']

data['operating_system'] = data.apply(recover_os, axis=1)

In [23]:
data['operating_system'].value_counts()

operating_system
Windows 11 Pro     225
Windows 11 Home     31
Windows 10 Pro      25
Unknown             23
Mac OS              13
Windows 10 Home      4
Others               3
Name: count, dtype: int64

In [24]:
data.dropna(subset=['Price'], inplace=True)

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 292 entries, 0 to 291
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             292 non-null    object
 1   Brand             292 non-null    object
 2   Price             292 non-null    float64
 3   Rating            51 non-null     float64
 4   operating_system  290 non-null    object
 5   ram               291 non-null    float64
 6   disk_size         292 non-null    float64
 7   Reviews           292 non-null    int64
 8   display_size      290 non-null    float64
dtypes: float64(5), int64(1), object(3)
memory usage: 22.8+ KB

In [26]:
data.tail(15)

,Title,Brand,Price,Rating,operating_system,ram,disk_size,Reviews,display_size
277,Apple 2026 MacBook Neo 13-inch Laptop with A18...,APPLE,599.00,4.8,Mac OS,8.0,256.0,107,13.0
278,Apple 2026 MacBook Neo 13-inch Laptop with A18...,APPLE,599.00,4.8,Mac OS,8.0,256.0,107,13.0
279,Apple 2026 MacBook Neo 13-inch Laptop with A18...,APPLE,599.00,4.8,Mac OS,8.0,256.0,107,13.0
280,Apple 2026 MacBook Neo 13-inch Laptop with A18...,APPLE,599.00,4.8,Mac OS,8.0,256.0,107,13.0
281,Apple 2026 MacBook Neo 13-inch Laptop with A18...,APPLE,599.00,4.8,Mac OS,8.0,256.0,107,13.0
282,Apple 2026 MacBook Neo 13-inch Laptop with A18...,APPLE,599.00,4.8,Mac OS,8.0,256.0,107,13.0
283,"Lenovo Laptop Computer, IdeaPad Slim 3 2026, 1...",LENOVO,439.98,4.6,Windows 11 Home,8.0,512.0,20,15.3
284,HP 15.6” Ultrabook Laptop • 16GB RAM • 1.1TB S...,HP,299.97,5.0,Windows 11 Pro,16.0,128.0,2,15.6
285,HP 15.6” Ultrabook Laptop • 16GB RAM • 1.1TB S...,HP,299.97,5.0,Windows 11 Pro,16.0,128.0,2,15.6
286,HP 15.6” Ultrabook Laptop • 16GB RAM • 1.1TB S...,HP,299.97,5.0,Windows 11 Pro,16.0,128.0,2,15.6
287,HP 15.6” Ultrabook Laptop • 16GB RAM • 1.1TB S...,HP,299.97,5.0,Windows 11 Pro,16.0,128.0,2,15.6
288,HP 15.6” Ultrabook Laptop • 16GB RAM • 1.1TB S...,HP,299.97,5.0,Windows 11 Pro,16.0,128.0,2,15.6
289,HP 15.6” Ultrabook Laptop • 16GB RAM • 1.1TB S...,HP,299.97,5.0,Windows 11 Pro,16.0,128.0,2,15.6
290,HP 15.6” Ultrabook Laptop • 16GB RAM • 1.1TB S...,HP,299.97,5.0,Windows 11 Pro,16.0,128.0,2,15.6
291,HP 15.6” Ultrabook Laptop • 16GB RAM • 1.1TB S...,HP,299.97,5.0,Windows 11 Pro,16.0,128.0,2,15.6

## 3. Preliminary Insights

In [27]:
#Top 5 most expensive laptops and their specs
top_expensive = data.nlargest(5, 'Price')[['Brand', 'Price', 'ram', 'disk_size']]

# Manual correction for Row 4: Title shows '8TB' in a complex format (2x4TB RAID 0)
# This ensures the disk_size reflects its true high-end specs for the analysis.
data.loc[4, 'disk_size'] = 8192

In [29]:
print(top_expensive)

    Brand     Price    ram  disk_size
0    DELL  14999.00   24.0    32768.0
1  MAVARK  12999.00   96.0    24576.0
2  LENOVO  11999.00  192.0    18432.0
3  LENOVO   9999.99   16.0     8192.0
4     MSI   9889.00  128.0    20480.0

In [30]:
# حفظ الداتا النظيفة في ملف جديد
data.to_csv('cleaned_amazon_laptops.csv', index=False)